# Generated by Django 4.1.7 on 2023-04-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='non', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sharing_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
