# Generated by Django 4.1.7 on 2023-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_offer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_offer_request_status',
            field=models.BooleanField(default=False),
        ),
    ]
